# Generated by Django 5.2 on 2025-04-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='Description coming soon', max_length=2000),
            preserve_default=False,
        ),
    ]
